
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gas_development
test:
  <<: *default
  database: gas_test

production:
  <<: *default
  database: gas_production
  username: gas
  password: <%= ENV['GAS_DATABASE_PASSWORD'] %>
